name: Continuos Integration workflow

on: pull_request

jobs:
  ci-menu-public-portal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: menu-public-portal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Tests
        run: npm test
