name: Branch Deployment workflow

on:
  workflow_dispatch:
  push:
    branches:
      - vnext

env:
  VERCEL_PROJECT_ID: ${{ secrets.DEV_VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.DEV_VERCEL_ORG_ID }}

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: menu-public-portal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: vercel -t ${{ secrets.DEV_VERCEL_TOKEN }}
