name: Branch Deployment workflow

on:
  workflow_dispatch:
  push:
    branches:
      - vnext

env:
  HEROKU_API_KEY: ${{ secrets.DEV_HEROKU_API_KEY }}
  IMAGE_NAME: registry.heroku.com/${{ secrets.DEV_HEROKU_APP_NAME }}/web

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: menu-public-portal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login heroku
        run: heroku container:login
      - name: Build docker image
        run: docker build --build-arg SITE_URL=${{secrets.DEV_SITE_URL}} -t ${{ env.IMAGE_NAME }} .
      - name: Deploy docker image
        run: docker push ${{ env.IMAGE_NAME }}
      - name: Release
        run: heroku container:release web -a ${{ secrets.DEV_HEROKU_APP_NAME }}
