name: Production Deployment workflow

on:
  push:
    branches:
      - main

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: menu-public-portal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy
        run: vercel -t ${{ secrets.VERCEL_TOKEN }} --prod
